### ISSUE TITLE
Checking an Application from Company Marks All Apps from Company as Completed

### ISSUE THREAD

**Issue by kevin1015wang** [csaye/interning.dev#10]
After marking one application from a company as completed, multiple jobs from the company are also marked as completed.

https://github.com/csaye/interning.dev/assets/38193800/cb405013-fff8-4d41-9bea-7cf521e03698

**Comment by csaye** [comment]
I'm looking into this, thanks for letting me know. I'm going to have to do some restructuring now that the README format changed

**Comment by csaye** [comment]
I've restructured how internships are parsed so that all internships under one company are grouped together. To me, this is an easier view to look at, but I might add an option in the future to mark each internship individually. For now this should be solved
