### ISSUE TITLE
New README Design Broke Site

### ISSUE THREAD

**Issue by kevin1015wang** [csaye/interning.dev#9]
The new README layout on the Pitt CSC repo has left the interning.dev site stuck at loading...

**Comment by michaelfromyeg** [comment]
For a bit of added context...

![image](https://github.com/csaye/interning.dev/assets/35978975/1feb49be-611d-45d7-ab5e-1853891c288c)

**Comment by csaye** [comment]
I'm getting to work on fixing this! Thanks for the heads up

**Comment by csaye** [comment]
The site should at least be usable again! I'm going to do some work to make it play nicely with the new format. Thanks for bringing this to my attention

**Comment by michaelfromyeg** [comment]
thanks for addressing it so quick, it's awesome project!
